### ISSUE TITLE
Uncaught (in promise) Error: Invalid params

### ISSUE THREAD

**Issue by idimon4uk** [blockxlabs/aiwa#10] opened 2018-12-27 14:01 UTC
Use version beta 0.0.3 from Chrome Web Store
Mastery
 >
var tx = {
    from : "0xa07d41f8e554c2ec0fa02847de76f8e8af147f9512fc3b3b4f26740345b0c08d",
    to:"0xa03f466dbbb97c15b425807f58b9d6a3caa9c935b2eae32a2c70a7e69eef6ac9",
    value:0.001
}
aionweb3.eth.sendTransaction(tx)

I receive in popup window this error

Uncaught (in promise) Error: Invalid params
    at Object.InvalidResponse (mainapp.bundle.js:19)
    at s.send (mainapp.bundle.js:63)
    at b.n [as sendRawTransaction] (mainapp.bundle.js:19)
    at mainapp.bundle.js:109
<
![image](https://user-images.githubusercontent.com/16037887/50482652-61419600-09f0-11e9-9be6-452fbfdaaf2c.png)

![image](https://user-images.githubusercontent.com/16037887/50482641-4d962f80-09f0-11e9-9674-1b0bc7580a34.png)
![image](https://user-images.githubusercontent.com/16037887/50485428-f6975700-09fd-11e9-996a-130e965a3565.png)

**Comment by jonpurdy-blockxlabs** [comment] 2018-12-28 20:38
Hi, if the issue is what I think it is (issue with estimateGas), could you try downloading the 0.4 version from our Github release? It is fixed in that.

**Comment by JesseAbram** [comment] 2019-01-08 19:31
Hey, so I could not reproduce the error in version 1.0. However I did notice you are trying to send 0.001 value. The Aion blockchain does not recognize decimals that is more of a front end thing. 1 Aion = 1000000000000000000. There is a more detailed guide [here](https://github.com/aionnetwork/aion/wiki/Aion-Terminology)

**Closed** 2019-01-08 19:32 UTC
