### ISSUE TITLE
Aiwa User Advisory Board Request 

### ISSUE THREAD

**Issue by kzeine** [blockxlabs/aiwa#8] opened 2018-12-06 18:25 UTC
# Overview

AIWA is a browser extension for Chrome. It allows users to interact with DApps and developer tools on the Aion Network. These DApps can be authorized to perform transactions without being exposed to users’ private keys or seed words. AIWA’s mission is to enable developers and users to interact with each other, the Aion Network, and DApps.

The purpose of this exercise it to ensure that AIWA is intuitive. A user familiar with Aion Network should not experience friction while using it. If there are any points of friction, we'd like to identify them so that we can take action to correct them.

**Rewards**
Rewards for this bounty is 50 AION for a successful submission that meets the general rules and acceptance criteria. Rewards will be disbursed within a 2-week window from the day of the deadline.
*We might also pay out bounties for UI/UX feedback depending on the severity.

# Scenario Descriptions
 
As a user, I should be able to:
- Create and export vaults 
- Create and import wallets 
- Switch between network providers
- Add and send AION and other Tokens between wallets
 
# Prerequisites
 
- [Install AIWA](https://getaiwa.com)
- [Get mastery AION](https://faucets.blockxlabs.com/) 
- Have private key for an existing wallet that has mastery test AION in it
 
# Test Scripts & Tasks
 
1. **Create a new vault:** As a user, I should be able to successfully install AIWA and create a new vault 
2. **Create a second wallet:** As a user, I should be able to view wallets and add a second wallet 
3. **Import an existing wallet:** As a user, I should be able to import a wallet using a private key (see below) and renaming the wallet. 
Private key to be used: 
d231b4b4977d7750cd06b22c536e17227db55dfbfcfb575295860cc678b6976a7a04aa6b5b40f6c8704e31e68d8366f4bcdedd8b6fbcab0e54ba8afdd1e7b303
_Please note: this private key is shared and is NOT to be used for mainnet Aion Coin_ 
4. **Export my vault:** As a user, I should be able to export my vault using my password into a file starting with UTC-…
5. **Switch to mainnet provider:** As a user, I should be able to switch between Mastery and Mainnet networks and confirm that I’m connected after each switch. 
6. **Send AION between wallets:** As a user, I should be able to choose my wallet of choice and send AION to the second wallet created in step 2 while being able to confirm the transaction before and after sending 
7. **Add Patel token to a wallet:** As a user, I should be able to add a token to my wallet using the KPT smart contract address (see below) and verify it has been added. 
KPT smart contact to be added: 0xa0c57411498e927dfe19482f1aa5296ec1a8d3be758048fac9ca6c57a4dbc277
8. **Send Patel token to another wallet:** As a user, I should be able to send KPT Tokens to the second wallet created in step 2 and verify the amount has been received 
9.  **“Add token” sending TST token without adding it first:** As a user, I should be able to send token without having to add it first (follow steps below)
a. Go to getaiwa.com/sample-dapp/
b. Click the SEND TOKEN button
c. Pop up for "Would you like to add test token?" should show up, click Submit
d. Verify that message "test token successfully added" is displayed

# Acceptance Criteria

Please submit your responses as replies to this issue and include the email address you signed up with to the UAB Program. In your response, include the result for each of the 9 steps included in the tasks above i.e. provide "success", "fail", or "help".
- If there is a fail, provide a point-form description of why it failed.
- If you're not sure, or if clarification is required, provide "help" with point-form clarification questions.
- Feel free to provide feedback even if the task was a "success".

For example:
1. success
2. fail
\- able to view wallets and click the + button, but wallet not created
3. success
\- works, but button looks odd
4. help
\- where is the export vault button?
.
.
.

# Eligibility 

Only users that have applied directly to the [User Advisory Board](https://aionnetwork.typeform.com/to/EhufDv) and have been approved by the Aion Foundation can participate in this bounty.

Only the first response from a user will be eligible for AION rewards. In the event of identical responses from different users, only the first submitted response (based on time of submission) will be eligible for AION rewards.

**Deadline**
Responses must be submitted within 1 week of the official email request sent to the User Advisory Board members.

# Guidance

For assistance on this issue, you may directly reach out to the BlockX Team at aiwa@getaiwa.com or to bounty@aion.network.

**Comment by abellinii** [comment] 2018-12-07 01:19
1. Success.

2. Success.

3. Success.
- After the Import if I click on the gear in the wallet address to export/import. The last import continues to show up and 50% of the division is underneath both the layer above and below. So you are unable to export or import another wallet or key. This returned to the normal import/export screen after around a minute.

4. Fail
- Able to open and see the export button. On hover before clicking it shows the color change and then once clicked nothing happens. Afterward, the color does not change on hover and still nothing happens when it is clicked.

5. Success
-Although there is nothing to confirm the change of network. One instance it did show an error when it couldn't connect to the new network. It would allow for a better experience if there was a similar pop to acknowledge the successful connection to the new network.

6. Success.
-Directly after sending the transaction the amount displayed as the Aion balance changes to a random number. It shows for around 3 seconds and then reverts back to the original value before the transaction was sent. In both transactions I did, I sent 2 Aion from the original 200 received when the wallet was imported. The first time it displayed 87 Aion then reverted back to 200 Aion and the second, 102 Aion and then once again reverting back to 198 Aion. Also, the balance does not change automatically once the transaction has been verified but does if you click and view something else on the interface.

7. Success.

8.Success.
- The same error occurs with the change of balance stated above in number 6. Also if you have the balance set to Patel token and then change to a different wallet the screen still shows the KPT(Patel token) even if the token has not been added to the wallet and the balance is 0.

9.
a. Success
b. Success
c. Success
- A pop up occurs but does not state the question "Would you like to add test token?"
d.Success
- "test token successfully added" does not pop up but the wallet shows a confirmed transaction which states 'Sent 0 Patel token' with a transaction hash 0x86150951c4b4d0f61d586a472da2d523ba5acbc14fd78b28848ec6ff8da1b3df.



Overall the display and user experience is intuitive. Once the bugs stated above are taken care of I think the design is fairly user-friendly and similar to meta mask.

email: wadejamesabel@gmail.com

**Comment by stevebayerin** [comment] 2018-12-07 05:48
1. Sucess
2. Success
3. Success
4. Success
- User needs feedback to show that the file has been downloaded to their computer or they won't know an action has taken places unless they look for a downloaded file.
5. Success
6. Success
- NRG required to send transaction may need a help link for new users who may be unfamiliar with what NRG is.
- NRG Limit may need a help link for new users who may be unfamiliar with what an NRG limit is.
- Hex Data may need a help link for new users who may be unfamiliar with what is Hex Data.
7. Success
8. Success
9. 
a. Success
b. Help
- Success on first visit to the page.
- Strange behavior on second visit to the page.
--  On second visit to page, wallet screen popped up with previously used wallet appearing as wallet to send from.
--- I wanted to change from my secondary wallet to Aiwa's demo wallet without closing window..
- No response on third visit to page.
c. Help
- Success on first visit of the page and attempt at sending token, popup appeared but it did not have the words "Would you like to add test token?".
- On second visit to page, Hex data appeared next to send button instead of pop up.
-- Clicking the send button the second time on second visit to page, added more hex data next to send button and no pop up.
d. Fail
- On first visit to the page and attempt at sending token, message appeared but it did not have the words "test token successfully added".
- On first visit to the page and attempt at sending token, transaction appears as failed. This may be because I visited this page and tried to send a token before I figured out how to add a Patel smart contract.

This is very similar to Metamask and Metamask users would feel at home. However, new users to crypto-currency may be confused with what NRG is, what NRG Limit is and what is Hex Data.

email: stevebayerin@gmail.com

**Comment by AndyVelly** [comment] 2018-12-07 15:12
1. Success
2. Success
3. Success
4. Success
5. Success
6. Success
7. Success
8. Help - Unclear on how to add Patel token in order to send it between wallets, I've added the token in step 7. but the balance is zero.
9. a. success
9. b. success
9. c. Fail - no popup asking to add test token
9. d. Fail - attempted to send test token anyway, the token failed to send

Intuitive and smooth to use, nice UI.
email: andrew.vellekoop@gmail.com

**Comment by crypthusiast** [comment] 2018-12-08 15:30
1. success
2. success
3. success
4. Success
5. Success
6. success
7. success
8. HELP, didn't understand how to transfer the aion in the wallet to kpt
9. Help, didn't understand

**Comment by EncryptedBear** [comment] 2018-12-09 11:12
1. Success.

2. Success.
- Adding new wallets through the "+" button is a good, but not too obvious decision, 
not immediately noticeable, you need some time to understand this.

3. Success.

4. Success.
- The result of the vault export is not clear, user should be asked where he would like to save/download the UTC file.

5. Success.
- There is nothing to confirm the change of the network.

6. Success.
- There is no any visible incoming Aion transactions on the receiving wallet

7. Success.
- Adding tokens through the ">" button is a good, but not too obvious decision, not immediately noticeable, you need some time to understand this.

8. Success.
- There is no any visible incoming Token transactions on the receiving wallet

9. 
a. Success.
- Link opens without any troubles.
b. Success.
- "Send Token" button works well. Should to say you need to switch to Aion from KPT before creating new transaction sending 100 TEST tokens. (Other way you will try to send 0 KPT)
c. Failed.
- There is no any "Would you like to add test token?" on the showing pop up! You can see just "Aiwa Window" creating sending transaction to the unknown contract.
d. Failed.
- Transaction sending 100 TEST tokens failed anytime. No message"test token successfully added" is displayed.

Interface is intuitive and is very similar to Metamask so it is very easy to use it. But should be fixed some minor troubles/drawbacks. Should to say few times i had to wait loading status for several seconds. But in common UI is very nice.

**Comment by EncryptedBear** [comment] 2018-12-09 11:15
1. Success.

2. Success.
- Adding new wallets through the "+" button is a good, but not too obvious decision, 
not immediately noticeable, you need some time to understand this.

3. Success.

4. Success.
- The result of the vault export is not clear, user should be asked where he would like to save/download the UTC file.

5. Success.
- There is nothing to confirm the change of the network.

6. Success.
- There is no any visible incoming Aion transactions on the receiving wallet.

7. Success.
- Adding tokens through the ">" button is a good, but not too obvious decision, not immediately noticeable, you need some time to understand this.

8. Success.
- There is no any visible incoming Token transactions on the receiving wallet.

9. 
a. Success.
- Link opens without any troubles.
b. Success.
- "Send Token" button works well. Should to say you need to switch to Aion from KPT before creating new transaction sending 100 TEST tokens. (Other way you will try to send 0 KPT)
c. Failed.
- There is no any "Would you like to add test token?" on the showing pop up! You can see just "Aiwa Window" creating sending transaction to the unknown contract.
d. Failed.
- Transaction sending 100 TEST tokens failed anytime. No message"test token successfully added" is displayed.

Interface is intuitive and is very similar to Metamask so it is very easy to use it. But should be fixed some minor troubles/drawbacks. Should to say few times i had to wait loading status for several seconds. But in common UI is very nice.

**Comment by EncryptedBear** [comment] 2018-12-09 11:17
1. Success.

2. Success.
- Adding new wallets through the "+" button is a good, but not too obvious decision, 
not immediately noticeable, you need some time to understand this.

3. Success.

4. Success.
- The result of the vault export is not clear, user should be asked where he would like to save/download the UTC file.

5. Success.
- There is nothing to confirm the change of the network.

6. Success.
- There is no any visible incoming Aion transactions on the receiving wallet.

7. Success.
- Adding tokens through the ">" button is a good, but not too obvious decision, not immediately noticeable, you need some time to understand this.

8. Success.
- There is no any visible incoming Token transactions on the receiving wallet.

9.
a. Success.
- Link opens without any troubles.

b. Success.
- "Send Token" button works well. Should to say you need to switch to Aion from KPT before creating new transaction sending 100 TEST tokens. (Other way you will try to send 0 KPT)

c. Failed.
- There is no any "Would you like to add test token?" on the showing pop up! You can see just "Aiwa Window" creating sending transaction to the unknown contract.

d. Failed.
- Transaction sending 100 TEST tokens failed anytime. No message"test token successfully added" is displayed.

Interface is intuitive and is very similar to Metamask so it is very easy to use it. But should be fixed some minor troubles/drawbacks. Should to say few times i had to wait loading status for several seconds. But in common UI is very nice.

**Comment by crose99** [comment] 2018-12-09 19:57
1. Success
2. Success
3. Success
4. Success
5. Success
6. Success
7. Success - Worked no problem, but found the Navigation to be a little confusing and not very intuitive.
8. Success
9.
A. Success
B.Success
C. Fail - No Popup Occurred
D. Fail -
First Attempt - No Verify message displayed, Sent 0 Patel-TX id 0xab38135565f14e08785d6417167b9e09259fd8c1e3b991ad2a06fb1ea96d998f

Second Attempt:
Received 'Revert Error' , TX id 0xdb43797a38663bec9a80005e599c300d612f49d7ec2eb3cf8ff3e737e656259f

email: calvinrose@gmail.com

**Comment by Knevil** [comment] 2018-12-10 18:47
email: yalafreniere@gmail.com

1. success
2. success
3. success
4. success
5. success
6. success
7. success
8. success
9.a) success
   b) success
   c) fail -Pop up for "Would you like to add test token?" did not show up (see attachment for the only thing that did show up)
   d) fail -message "test token successfully added" did not show up (see attachment for the only thing that did show up)
![aiwa test](https://user-images.githubusercontent.com/38870958/49753651-0c78ee00-fc82-11e8-8c5e-1ebfcdcbd934.PNG)

**Comment by JesseAbram** [comment] 2018-12-11 21:02
Hey all, just checked myself with version 0.3 the latest release and this works. Please use that build to test again; cheers.

**Comment by Knevil** [comment] 2018-12-11 21:13
doesnt seem available through chrome web store.

**Comment by JesseAbram** [comment] 2018-12-11 21:22
ya, it is under review now so whenever it clears. If you can either wait, or download the build from here https://github.com/blockxlabs/aiwa/releases . Go to manage extensions on chrome, make sure developer mode is on and click load unpacked. That should allow you to run 0.3.

**Comment by Knevil** [comment] 2018-12-11 21:46
gotcha, thank you!

**Comment by Knevil** [comment] 2018-12-12 17:49
ok so i installed version 0.3 and redid all steps which gave me the same
results. is my original reply on github good enough since nothing changed?

**Comment by MrLova001** [comment] 2018-12-12 18:17
1. Success
2. Success
3. Success
4. Success
5. Success
6. Success
7. Navigation is a bit slow between wallets, and some times it does take a bit longer navigating the wallets
8. Success
9. a). Success
    b). Success
    c). Failed - pop-up showed trying to send 0 KPT (Failed 3 tries with different wallets) Screenshot attached. 
    d). Failed

--------
![capture](https://user-images.githubusercontent.com/27823268/49889687-72ac6f00-fe42-11e8-890b-39224ed1b19f.PNG)

**Comment by jonpurdy-blockxlabs** [comment] 2018-12-12 18:30
Hi @Knevil , I'm the Project Manager for AIWA. Since you've gotten the same result, there's no need to update your reply.
My fault for not putting in the original request to use the Github version since that the most up-to-date. And thanks for your help!

**Comment by bitjefe** [comment] 2018-12-13 00:14
1. success
2. success (UX/UI comment:  Took awhile to find where this option was.  Maybe add "on-hover" not or a + button on the main screen to add a wallet instead of the down arrow and then + with no text instructions on what it does. also the + is a little dark compared to the background.)

3. success
4. success
5. success
6. success (UX/UI Comment: inter-wallet navigation was slow. Took multiple clicks on the drop down arrow and each wallet before it registered the action)

7. success (although unclear it had to be added to wallet 3 to show up)
8. success (can only see the KPT token on wallet2, created in step 2, and wallet3, imported, if i start with the wallet i add the KPT token the switch to those wallets.)
9.
  a. success
  b. success
  c. success.  (failed on the first attempt with the wallet created in step 2 but i switched to the initially created wallet and it worked as intended)

![screen shot 2018-12-12 at 6 11 15 pm](https://user-images.githubusercontent.com/42820202/49906954-ba7ac880-fe39-11e8-9d8d-1a6cd9220148.png)

  d. success

![screen shot 2018-12-12 at 6 11 47 pm](https://user-images.githubusercontent.com/42820202/49906959-c1a1d680-fe39-11e8-846f-3fd000c9ce77.png)



email: jwiand.3p@gmail.com

**Comment by abellinii** [comment] 2018-12-13 04:34
I have tested the latest version of the wallet and edited my original comment above @jonpurdy-blockxlabs

**Closed** 2019-01-28 15:04 UTC
Labels: bounty
